# general settings
name: train_LightingFormer
model_type: LightingFormerModel
num_gpu: auto
manual_seed: 0

l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: True


gt_size: 256


# dataset and data loader settings
datasets:
  train:
    name: LOL
    type: RealESRGANPairedDataset
    dataroot_gt: E:\Downloads_G\our485\high
    dataroot_lq: E:\Downloads_G\our485\low
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
  # Uncomment these for validation
  val:
    name: validation
    type: PairedDataset
    dataroot_gt: E:\Downloads_G\eval15\high
    dataroot_lq: E:\Downloads_G\eval15\low
    io_backend:
      type: disk


# network structures
network_g:
  type: LightingFormer
  in_chans: 3
  img_size: 256
  patch_size: 4
  window_size: 8
  img_range: 1.
  depths: [ 2, 2, 2, 2]
  depths_decoder: [ 2, 2, 2, 2 ]
  embed_dim: 96
  num_heads: [ 3, 6, 12, 24 ]

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True
# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]
  optim_d:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: !!float 1
    reduction: mean
  # perceptual loss (content and style losses)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  # gan loss
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

# validation settings
val:
  val_freq: !!float 5000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
    niqe: # metric name, can be arbitrary
      type: calculate_niqe
      crop_border: 0
      #      crop_border: 4
      convert_to: y
      better: lower

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
